import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'

const navigationConfig = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'innovationInstitute',
        path: '',
        title: 'Innovation Institute',
        translateKey: 'nav.innovationInstitute',
        icon: 'innovationInstitute',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'innovationInstitute.valueProp',
                path: '/value-proposition',
                title: 'Value Proposition Generator',
                translateKey: 'nav.innovationInstitute.valueProp',
                icon: 'valueProp',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'innovationInstitute.marketIntel',
                path: '/market-intelligence',
                title: 'Market Intelligence',
                translateKey: 'nav.innovationInstitute.marketIntel',
                icon: 'marketIntel',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'innovationInstitute.sentiment',
                path: '/sentiment-analysis',
                title: 'Sentiment Analysis',
                translateKey: 'nav.innovationInstitute.sentiment',
                icon: 'sentiment',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'ossReviewer',
        path: '',
        title: 'OSS Reviewer',
        translateKey: 'nav.ossReviewer',
        icon: 'ossReviewer',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'ossReviewer.policyRag',
                path: '/policy-advisor',
                title: 'Policy Advisor',
                translateKey: 'nav.ossReviewer.policyRag',
                icon: 'policyRag',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'ossReviewer.deadlineTracker',
                path: '/deadline-tracker',
                title: 'Deadline Tracker',
                translateKey: 'nav.ossReviewer.deadlineTracker',
                icon: 'deadlineTracker',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'ossReviewer.formPrefiller',
                path: '/form-prefiller',
                title: 'Form Pre-filler',
                translateKey: 'nav.ossReviewer.formPrefiller',
                icon: 'formPrefiller',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'library',
        path: '',
        title: 'Library',
        translateKey: 'nav.library',
        icon: 'library',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'library.semanticSearch',
                path: '/semantic-search',
                title: 'Semantic Search',
                translateKey: 'nav.library.semanticSearch',
                icon: 'semanticSearch',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'library.citationSynthesis',
                path: '/citation-synthesis',
                title: 'Citation & Synthesis',
                translateKey: 'nav.library.citationSynthesis',
                icon: 'citationSynthesis',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'library.readingAssistant',
                path: '/reading-assistant',
                title: 'Reading Assistant',
                translateKey: 'nav.library.readingAssistant',
                icon: 'readingAssistant',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'ugAdvising',
        path: '',
        title: 'UG Advising',
        translateKey: 'nav.ugAdvising',
        icon: 'ugAdvising',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'ugAdvising.degreeAudit',
                path: '/degree-audit',
                title: 'Degree Audit',
                translateKey: 'nav.ugAdvising.degreeAudit',
                icon: 'degreeAudit',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'ugAdvising.successPredictor',
                path: '/success-predictor',
                title: 'Success Predictor',
                translateKey: 'nav.ugAdvising.successPredictor',
                icon: 'successPredictor',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'ugAdvising.peerMatching',
                path: '/peer-matching',
                title: 'Peer Matching',
                translateKey: 'nav.ugAdvising.peerMatching',
                icon: 'peerMatching',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'applicantReview',
        path: '',
        title: 'Applicant Review',
        translateKey: 'nav.applicantReview',
        icon: 'applicantReview',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'applicantReview.bibliometric',
                path: '/bibliometric-analysis',
                title: 'Bibliometric Analysis',
                translateKey: 'nav.applicantReview.bibliometric',
                icon: 'bibliometric',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'applicantReview.alignmentScoring',
                path: '/alignment-scoring',
                title: 'Alignment Scoring',
                translateKey: 'nav.applicantReview.alignmentScoring',
                icon: 'alignmentScoring',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'applicantReview.biasMitigation',
                path: '/bias-mitigation',
                title: 'Bias Mitigation',
                translateKey: 'nav.applicantReview.biasMitigation',
                icon: 'biasMitigation',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
