import {
    PiHouseLineDuotone,
    PiLightbulbDuotone,
    PiChartLineUpDuotone,
    PiMicrophoneStageDuotone,
    PiFlaskDuotone,
    PiShieldCheckDuotone,
    PiChatCircleTextDuotone,
    PiCalendarCheckDuotone,
    PiScanDuotone,
    PiBooksDuotone,
    PiMagnifyingGlassDuotone,
    PiTableDuotone,
    PiBookOpenDuotone,
    PiGraduationCapDuotone,
    PiPathDuotone,
    PiChartBarDuotone,
    PiUsersDuotone,
    PiUserFocusDuotone,
    PiArticleDuotone,
    PiTargetDuotone,
    PiEyeSlashDuotone,
    PiMegaphoneDuotone,
    PiChartPieSliceDuotone,
    PiChatTeardropTextDuotone,
    PiTrendUpDuotone,
} from 'react-icons/pi'

const navigationIcon = {
    home: <PiHouseLineDuotone />,
    innovationInstitute: <PiFlaskDuotone />,
    valueProp: <PiLightbulbDuotone />,
    marketIntel: <PiChartLineUpDuotone />,
    sentiment: <PiMicrophoneStageDuotone />,
    ossReviewer: <PiShieldCheckDuotone />,
    policyRag: <PiChatCircleTextDuotone />,
    deadlineTracker: <PiCalendarCheckDuotone />,
    formPrefiller: <PiScanDuotone />,
    library: <PiBooksDuotone />,
    semanticSearch: <PiMagnifyingGlassDuotone />,
    citationSynthesis: <PiTableDuotone />,
    readingAssistant: <PiBookOpenDuotone />,
    ugAdvising: <PiGraduationCapDuotone />,
    degreeAudit: <PiPathDuotone />,
    successPredictor: <PiChartBarDuotone />,
    peerMatching: <PiUsersDuotone />,
    applicantReview: <PiUserFocusDuotone />,
    bibliometric: <PiArticleDuotone />,
    alignmentScoring: <PiTargetDuotone />,
    biasMitigation: <PiEyeSlashDuotone />,
    campusReputation: <PiMegaphoneDuotone />,
    discourseDashboard: <PiChartPieSliceDuotone />,
    sentimentFeed: <PiChatTeardropTextDuotone />,
    buzzAnalytics: <PiTrendUpDuotone />,
}

export default navigationIcon

